ansible-demo:
	ansible-playbook --inventory inventory.yml --user vagrant --private-key \
		.vagrant/machines/default/virtualbox/private_key playbook.demo.yml

ansible-sinatra:
	ansible-playbook --inventory inventory.yml --user vagrant --private-key \
		.vagrant/machines/default/virtualbox/private_key playbook.sinatra.yml
