- name: Run local command
  hosts: localhost
  tasks:
  - name: Remove existing app bundle
    command: rm -rf build/build.tgz
  - name: Create application bundle
    command: tar --exclude='./.git' -zcvf build/build.tgz .
  - name: Copy bundle to VM
    command: scp -i .vagrant/machines/default/virtualbox/private_key build/build.tgz vagrant@192.168.20.21:/home/vagrant/app

- name: Run server command
  hosts: server01
  tasks:
  - name: Delete all existing files
    command: rm -rf * !(build.tgz)
    args:
      chdir: app/
  - name: Extract app bundle
    command: tar -xvzf build.tgz
    command: rm -rf build.tgz
    args:
      chdir: app/
  - name: Run Sinatra application
    become: true
    command: sudo systemctl stop sinatra.service
    command: sudo systemctl start sinatra.service
